language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install coveralls
  - pip install .[test]

# command to run tests
script:
  - pytest

after_success:
    # submit code coverage information to coveralls
    - coveralls
